### ISSUE TITLE
Wrong parameter type in move  methods

### ISSUE THREAD

**Issue by ghost** [craiggrummitt/SpriteKitEasingSwift#1]
In all move methods there is a parameter of `CGVector`type to designate `from` or `to` data. This parameter suppose this is a delta from a given position but in methods this parameter is used as a `position` data.

So `CGPoint`will better suit for parameter type.

**Comment by craiggrummitt** [comment]
This came in from the Obj C port, but I agree - I have replaced CGVector with CGPoint.
https://github.com/craiggrummitt/SpriteKitEasingSwift/commit/1586a754a0fa000c7bf0f990127a735044b0286a
