### ISSUE TITLE
Variable easing

### ISSUE THREAD

**Issue by bluelemonade** [craiggrummitt/SpriteKitEasingSwift#11]
hello,  your lib works great, feels like flash.

one wish, I need a way to ease a variable. in Tweener theres an nice option to ease everything.

regards

**Comment by craiggrummitt** [comment]
Hi @bluelemonade, glad you're finding it useful!

The library actually already has that capability to ease a variable. 

For example, the following would ease a variable from 0 to 100, printing its value as it eases.

```
let easingFunction = SKEase.getEaseFunction(.curveTypeElastic, easeType: .easeTypeInOut)
let action = SKEase.createFloatTween(0, end: 100, time: 10, easingFunction: easingFunction) { (node:SKNode, variableToEase:CGFloat) -> Void in
  print(variableToEase)
}
scene.run(action)
```
