### ISSUE TITLE
Cocoapods uses tag 0.10 instead of master

### ISSUE THREAD

**Issue by SonOfCrypto** [craiggrummitt/SpriteKitEasingSwift#12]
Hi Craig,

you fixed "Silencing warnings by changing M_PI to .pi" on your master, but in the podspecs you are telling to use tag 0.10. Could you maybe update the file?

Thx! :)

**Comment by craiggrummitt** [comment]
Thanks @janwagner, podspec should be updated now.

**Comment by SonOfCrypto** [comment]
great! thank you very much
